
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BREAK ELSE FALSE FOR IF INT LLADER LLAIZQ PARDER PARIZQ PRINT RETURN SYSTEMOUT TRUE WHILE cadena entero identificador igual mayorigual punto puntoycoma sumafor_loop : FOR PARIZQ INT identificador igual entero puntoycoma identificador mayorigual entero puntoycoma identificador suma suma PARDER LLAIZQ statement LLADERstatement : SYSTEMOUT PARIZQ cadena suma identificador PARDER puntoycoma'
    
_lr_action_items = {'FOR':([0,],[2,]),'$end':([1,20,],[0,-1,]),'PARIZQ':([2,19,],[3,21,]),'INT':([3,],[4,]),'identificador':([4,8,12,23,],[5,9,13,24,]),'igual':([5,],[6,]),'entero':([6,10,],[7,11,]),'puntoycoma':([7,11,25,],[8,12,26,]),'mayorigual':([9,],[10,]),'suma':([13,14,22,],[14,15,23,]),'PARDER':([15,24,],[16,25,]),'LLAIZQ':([16,],[17,]),'SYSTEMOUT':([17,],[19,]),'LLADER':([18,26,],[20,-2,]),'cadena':([21,],[22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'for_loop':([0,],[1,]),'statement':([17,],[18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> for_loop","S'",1,None,None,None),
  ('for_loop -> FOR PARIZQ INT identificador igual entero puntoycoma identificador mayorigual entero puntoycoma identificador suma suma PARDER LLAIZQ statement LLADER','for_loop',18,'p_for_loop','analizador_lexico.py',77),
  ('statement -> SYSTEMOUT PARIZQ cadena suma identificador PARDER puntoycoma','statement',7,'p_statement','analizador_lexico.py',81),
]
